{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "huawei-elb-controller.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "huawei-elb-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  ak: {{ .Values.credentials.ak | quote }}
  sk: {{ .Values.credentials.sk | quote }}
  project-id: {{ .Values.credentials.projectId | quote }}
  region: {{ .Values.credentials.region | quote }}
{{- end }}
