apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "huawei-elb-controller.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "huawei-elb-controller.labels" . | nindent 4 }}
